//COLOR ACTIONS
export const UPDATE_HUE = 'UPDATE_HUE';
export const UPDATE_SATURATION = 'UPDATE_SATURATION';
export const UPDATE_LUMINANCE = 'UPDATE_LUMINANCE';

//IMAGE ACTIONS
export const SAVE_IMAGE_STATE = 'SAVE_IMAGE_STATE';
export const RESTORE_IMAGE_STATE = 'RESTORE_IMAGE_STATE';
